### ISSUE TITLE
Font color dark theme

### ISSUE THREAD

**Issue by DutchPete** [pengx17/logseq-laurel-theme#13]
I have this code snippet in my `custom.css` file:

```css
.dark-theme {
  --ls-primary-text-color: #FCE69F !important;
}
```
unfortunately, it does not work with Laurel despite `!important`, even though it does with the default and other themes.
